### ISSUE TITLE
Installation not properly

### ISSUE THREAD

**Issue by hirenpatelgit** [pamapa/react-oidc-context#28]
I have tried to install "react-oidc-context" but not able to install it properly.
I have removed node-module and try to install fresh but still not properly installed.
See below screen shot. When i tried to install it I am getting only this three file in node-module/react-oidc-context/...
<img width="374" alt="Screenshot 2021-06-01 at 1 39 29 PM" src="https://user-images.githubusercontent.com/18570717/120290513-065aaa00-c2e0-11eb-972c-eb34452b6371.png">

In order to use this library , do I need to install typescript npm?
Kindly help me.
Thank you.

**Comment by pamapa** [comment]
Thanks for reporting. Its not your fault but mine.

The 0.0.1-alpha4 is invalid published, i am setting up publishing via the pipeline. Need to fix this. Please use 0.0.1-alpha3 in the meantime...

**Comment by pamapa** [comment]
Can you test with 0.0.1-alpha5?

**Comment by pamapa** [comment]
fixed

**Comment by hirenpatelgit** [comment]
Thank you for update and I will try new version 0.0.1-alpha5.
