### ISSUE TITLE
Can't figure out how to handle redirect

### ISSUE THREAD

**Issue by wasabii** [pamapa/react-oidc-context#65]
The documentation doesn't mention what value should be put into redirect_url. Is it supposed to be to a route you create? Or does it crate it on it's own? If you have to create it, it should probably mention what to create and how to create it!

**Comment by pamapa** [comment]
settings coming from the oidc-client library are documented in that library.

See https://github.com/IdentityModel/oidc-client-js/wiki:
redirect_uri (string): The redirect URI of your client application to receive a response from the OIDC/OAuth2 provider.

This library (react-oidc-context) puts the userManager into a context to be accessible from the react application. Additionally it intercepts the redirects by looking at the query parameters and acts accordingly. Thus you need to setup a redirect_uri, which is inside you application, but you do not need to create that route.
See this block: https://github.com/pamapa/react-oidc-context/blob/6179e0e3e1d960e3cea4a842816233a70a918ab2/src/AuthProvider.tsx#L87

**Comment by wasabii** [comment]
Okay. So that the Context handles intercepting replies to the callback URL is the part I was missing. It doesn't seem to actually care about the path though, does it? It seems to run for every path. So, if any URL in the whole app uses state or code, it'll intercept it?
